### ISSUE TITLE
Not working in XCode 7.1

### ISSUE THREAD

**Issue by amccarri** [yuhua-chen/MCLog#33]
MCLog no longer crashing, but filter field no longer present in XCode 7.1 final (7B91b).

**Comment by zvjerka24** [comment]
Same issue... any solution? Some workaround?

**Comment by yuhua-chen** [comment]
Use [xcplugin_update.sh](https://gist.github.com/alexlee002/b87dbeac1f9fd896174b) to update UUID of new Xcode. Thanks to @alexlee002

**Comment by devxoul** [comment]
@yuhua-chen after using that MCLog causes crash :(

**Comment by devxoul** [comment]
@yuhua-chen After using that Xcode crashes :cry:

**Comment by yuhua-chen** [comment]
What's your OS version? Can you show me some logs? Still working on it. :dizzy_face:

**Comment by revolter** [comment]
#34 fixes this.

**Comment by revolter** [comment]
@yuhua-chen, didn't #34 fix this? The plugin was having set the UUID of the Xcode 7 beta, so Xcode 7.1 was not supported by it, hence it didn't appear.

**Comment by yuhua-chen** [comment]
The UUID of PR is right for Xcode 7.1, by following:
```
$ defaults read /Applications/Xcode\ 7.1.app/Contents/Info DVTPlugInCompatibilityUUID
7265231C-39B4-402C-89E1-16167C4CC990
```
I think it crashed by some reasons due to Xcode 7.1.

**Comment by revolter** [comment]
I understand, for me it didn't crash once, @devxoul, could you clone this project and build the project and tell us if it still crashes?

**Comment by devxoul** [comment]
@revolter, of course, wait for a minute.

**Comment by yuhua-chen** [comment]
@revolter @devxoul  what's your OS version? I found that it only crashed on OS El captain and Xcode 7.1.

**Comment by revolter** [comment]
I'm on OS X Yosemite 10.10.5

**Comment by yuhua-chen** [comment]
hmm...so weird. but mine is 10.10.5 too. It works fine. Have you tried this before?
`sudo xcodebuild -license`

**Comment by revolter** [comment]
I didn't say it crashed for me. So you previous comment might be correct, that it only crashes in El Capitan and Xcode 7.1

**Comment by devxoul** [comment]
`master` branch causes crash.

**Comment by revolter** [comment]
@devxoul on what OS version?

**Comment by devxoul** [comment]
- OS X 10.11.1 (Yosemite)
- Xcode 7.1

**Comment by lucianoks** [comment]
I'm able to use it on El Capitain (15B42) and Xcode 7.1 (7B91b) and 7.2 beta (7C46t) with this [solution](https://github.com/yuhua-chen/MCLog/issues/32#issuecomment-146582411).
But getting this [issue](https://github.com/yuhua-chen/MCLog/issues/35) in the process =/

**Comment by yuhua-chen** [comment]
I updated the plugin. It works on Xcode 7 right now. Try the newest commit(04c1cc1b) on master.

**Comment by lucianoks** [comment]
Hi, @yuhua-chen! I've tried your latest commit, but I'm still getting [this](https://github.com/yuhua-chen/MCLog/issues/35) issue. Only me?

**Comment by Visput** [comment]
@lucianoks Have the same issue on Xcode 7.1.1 (7B1005), El Capitan 10.11.1 (15B42).

**Comment by yuhua-chen** [comment]
Let's move to #35 issue since this plugin worked on Xcode 7.1 now.

**Comment by domhof** [comment]
Not working on El Capitan (10.11.2) and Xcode 7.2 either (filter field not present).

**Comment by WhiteTeeth** [comment]
Not working on Yosemite (10.10.5 ) and Version 7.2 (7C68) either (filter field not present). And xcplugin_update.sh works. Thanks @alexlee002 and @yuhua-chen!
